#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FallenLeaves.Resource", IsApplication=true)]

namespace FallenLeaves
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050009
			public const int factor_countNames = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int factor_sizeNames = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int factors = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int layout_ids = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int layout_names = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int sky_ids = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int sky_names = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int wind_dir_ids = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int wind_dir_names = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int wind_ids = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int wind_names = 2131034115;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int thumb = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int thumb02 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int thumb03 = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f030000
			public const int preferences_free = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int wallpaper = 2130903041;
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
