#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FallenLeaves.Resource", IsApplication=true)]

namespace FallenLeaves
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060009
			public const int factor_countNames = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int factor_sizeNames = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int factors = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int layout_ids = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int layout_names = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int sky_ids = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int sky_names = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int wind_dir_ids = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int wind_dir_names = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int wind_ids = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int wind_names = 2131099651;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int thumb = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int btnDontShow = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int btnGetFullVervion = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btnMarket = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int btnRate = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int btnRemind = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int btnSetWallpaper = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout2 = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainFreeLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RateLayout = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int wallpaper = 2130968577;
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
